"use client";

import { FormEvent, useRef, useState } from "react";
import { calculateCompatibility, type CompatResult } from "@/lib/bazi-compat";
import { copyToClipboard, exportReadingAsPDF } from "@/lib/pdf-export";
import { MethodologyModal } from "@/components/MethodologyModal";

const TIMEZONE_OPTIONS = [
  { label: "Kuala Lumpur (UTC+08)", value: "Asia/Kuala_Lumpur" },
  { label: "Singapore (UTC+08)", value: "Asia/Singapore" },
  { label: "Jakarta (UTC+07)", value: "Asia/Jakarta" },
  { label: "Bangkok (UTC+07)", value: "Asia/Bangkok" },
  { label: "Shanghai (UTC+08)", value: "Asia/Shanghai" },
  { label: "Hong Kong (UTC+08)", value: "Asia/Hong_Kong" },
  { label: "Taipei (UTC+08)", value: "Asia/Taipei" },
  { label: "Seoul (UTC+09)", value: "Asia/Seoul" },
  { label: "Tokyo (UTC+09)", value: "Asia/Tokyo" },
  { label: "Sydney (UTC+10)", value: "Australia/Sydney" },
  { label: "London (UTC+00/01)", value: "Europe/London" },
  { label: "New York (UTC-05/04)", value: "America/New_York" },
  { label: "Los Angeles (UTC-08/07)", value: "America/Los_Angeles" },
  { label: "UTC", value: "UTC" },
];

type PersonForm = {
  name: string;
  birthDate: string;
  birthTime: string;
  timeZone: string;
};

const EMPTY_PERSON: PersonForm = { name: "", birthDate: "", birthTime: "", timeZone: "Asia/Kuala_Lumpur" };

function PersonInputs({ person, setPerson, label }: { person: PersonForm; setPerson: (p: PersonForm) => void; label: string }) {
  return (
    <div className="compat-person">
      <h3>{label}</h3>
      <label>
        Name (optional)
        <input type="text" value={person.name} onChange={e => setPerson({ ...person, name: e.target.value })} placeholder="Name" />
      </label>
      <label>
        Date of Birth / 出生日期
        <input type="date" value={person.birthDate} onChange={e => setPerson({ ...person, birthDate: e.target.value })} required />
      </label>
      <label>
        Birth Time / 出生時間
        <input type="time" value={person.birthTime} onChange={e => setPerson({ ...person, birthTime: e.target.value })} />
        <span className="input-hint">Leave blank if unknown</span>
      </label>
      <label>
        Timezone
        <select value={person.timeZone} onChange={e => setPerson({ ...person, timeZone: e.target.value })}>
          {TIMEZONE_OPTIONS.map(tz => <option key={tz.value} value={tz.value}>{tz.label}</option>)}
        </select>
      </label>
    </div>
  );
}

export default function CompatibilityPage() {
  const [male, setMale] = useState<PersonForm>(EMPTY_PERSON);
  const [female, setFemale] = useState<PersonForm>(EMPTY_PERSON);
  const [result, setResult] = useState<CompatResult | null>(null);
  const [error, setError] = useState("");
  const [copySuccess, setCopySuccess] = useState(false);
  const [showMethodology, setShowMethodology] = useState(false);
  const resultPanelRef = useRef<HTMLElement>(null);

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError("");
    if (!male.birthDate || !female.birthDate) {
      setError("Please enter both dates of birth.");
      return;
    }
    try {
      const res = calculateCompatibility({
        male: { name: male.name, gender: "Male", birthDate: male.birthDate, birthTime: male.birthTime || undefined, timeZone: male.timeZone },
        female: { name: female.name, gender: "Female", birthDate: female.birthDate, birthTime: female.birthTime || undefined, timeZone: female.timeZone },
      });
      setResult(res);
    } catch (err) {
      setResult(null);
      setError(err instanceof Error ? err.message : "Something went wrong.");
    }
  }

  async function handleExportPDF() {
    if (!result || !resultPanelRef.current) return;
    try { await exportReadingAsPDF(resultPanelRef.current, "bazi-compatibility.pdf"); }
    catch (err) { console.error("Compat PDF export failed:", err); }
  }

  function handleShareText() {
    if (!result) return;
    const lines = [
      `BaZi Compatibility Analysis (八字合婚)`,
      `Male: ${male.name || "Person A"} — Day Master: ${result.maleChart.dayMaster.chinese} ${result.maleChart.dayMaster.pinyin} (${result.maleChart.dayMaster.element})`,
      `Female: ${female.name || "Person B"} — Day Master: ${result.femaleChart.dayMaster.chinese} ${result.femaleChart.dayMaster.pinyin} (${result.femaleChart.dayMaster.element})`,
      "",
      `Overall: ${result.percentage}% — ${result.overallRating}`,
      "",
      "Factors:",
      ...result.factors.map(f => `  ${f.nameZh} ${f.name}: ${f.score > 0 ? "+" : ""}${f.score} — ${f.description}`),
      "",
      `Generated by 神圣秘密 Divine Secrets`,
    ];
    if (copyToClipboard(lines.join("\n"))) {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
  }

  return (
    <main className="page-shell">
      <section className="hero-panel">
        <div className="hero-zh">八字合婚</div>
        <div className="divider" />
        <div className="hero-en">BaZi Compatibility</div>
        <p>
          Compare two birth charts for marriage and relationship compatibility using classical
          Chinese metaphysics methods — Day Master interaction, branch relationships, Na Yin,
          elemental complementarity, and Yin-Yang balance.
        </p>
        <button type="button" className="methodology-trigger" onClick={() => setShowMethodology(true)}>
          How It Works
        </button>
      </section>

      <section className="workspace-grid">
        <form className="panel compat-form" onSubmit={handleSubmit}>
          <h2>Birth Details / 出生資料</h2>
          <div className="compat-form-pair">
            <PersonInputs person={male} setPerson={setMale} label="♂ Male / 男方" />
            <PersonInputs person={female} setPerson={setFemale} label="♀ Female / 女方" />
          </div>
          <button type="submit">Analyze Compatibility / 分析合婚</button>
          {error && <p className="error-msg">{error}</p>}
        </form>

        <section className="panel result-panel" ref={resultPanelRef}>
          <h2>Compatibility Result / 合婚結果</h2>

          {!result ? (
            <p className="placeholder">
              Enter both birth details to see the compatibility analysis.
            </p>
          ) : (
            <>
              <div className="action-bar">
                <button type="button" onClick={handleExportPDF} className="action-btn export-btn">↓ Export PDF</button>
                <button type="button" onClick={handleShareText} className={`action-btn share-btn ${copySuccess ? "copied" : ""}`}>
                  {copySuccess ? "✓ Copied to Clipboard" : "⧉ Copy & Share"}
                </button>
              </div>

              <div className="compat-score">
                <div className="compat-score-circle">
                  <span className="compat-score-number">{result.percentage}%</span>
                  <span className="compat-score-rating">{result.overallRating}</span>
                </div>
              </div>

              <div className="compat-pillars-compare">
                <h3>Pillar Comparison / 四柱對比</h3>
                <table>
                  <thead>
                    <tr><th></th><th>Year 年</th><th>Month 月</th><th>Day 日</th><th>Hour 時</th></tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="compat-row-label">♂ {male.name || "Male"}</td>
                      <td>{result.maleChart.yearPillar.stem.chinese}{result.maleChart.yearPillar.branch.chinese}</td>
                      <td>{result.maleChart.monthPillar.stem.chinese}{result.maleChart.monthPillar.branch.chinese}</td>
                      <td>{result.maleChart.dayPillar.stem.chinese}{result.maleChart.dayPillar.branch.chinese}</td>
                      <td>{result.maleChart.hourPillar ? `${result.maleChart.hourPillar.stem.chinese}${result.maleChart.hourPillar.branch.chinese}` : "—"}</td>
                    </tr>
                    <tr>
                      <td className="compat-row-label">♀ {female.name || "Female"}</td>
                      <td>{result.femaleChart.yearPillar.stem.chinese}{result.femaleChart.yearPillar.branch.chinese}</td>
                      <td>{result.femaleChart.monthPillar.stem.chinese}{result.femaleChart.monthPillar.branch.chinese}</td>
                      <td>{result.femaleChart.dayPillar.stem.chinese}{result.femaleChart.dayPillar.branch.chinese}</td>
                      <td>{result.femaleChart.hourPillar ? `${result.femaleChart.hourPillar.stem.chinese}${result.femaleChart.hourPillar.branch.chinese}` : "—"}</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div className="compat-factors">
                <h3>Factor Breakdown / 合婚因素</h3>
                {result.factors.map((f) => (
                  <div key={f.name} className="compat-factor-row">
                    <div className="compat-factor-header">
                      <span className="compat-factor-name">{f.nameZh} {f.name}</span>
                      <span className={`compat-factor-score ${f.score > 0 ? "positive" : f.score < 0 ? "negative" : "neutral"}`}>
                        {f.score > 0 ? "+" : ""}{f.score}
                      </span>
                    </div>
                    <div className="compat-factor-bar">
                      <div
                        className={`compat-factor-fill ${f.score > 0 ? "positive" : f.score < 0 ? "negative" : "neutral"}`}
                        style={{ width: `${Math.abs(f.score) / f.maxScore * 100}%` }}
                      />
                    </div>
                    <p className="compat-factor-desc">{f.description}</p>
                  </div>
                ))}
              </div>

              <div className="compat-interpretation">
                <h3>Interpretation / 解讀</h3>
                <ReadingSections lines={result.interpretation} />
              </div>

              <div className="note-box">
                <p>BaZi compatibility (合婚) is one dimension of relationship analysis. It reflects energetic tendencies, not destiny. Mutual respect, communication, and effort remain the foundation of any relationship.</p>
              </div>
            </>
          )}
        </section>
      </section>

      <MethodologyModal isOpen={showMethodology} onClose={() => setShowMethodology(false)} title="How BaZi Compatibility Works / 八字合婚原理">
        <h3>Day Master Interaction / 日主關係</h3>
        <p>
          The Day Master (日主) represents your core identity. When comparing two charts, the five-element
          relationship between Day Masters reveals the fundamental dynamic: generating (supportive),
          same (understanding), or controlling (tension/structure).
        </p>

        <h3>Marriage Palace / 日柱婚姻宮</h3>
        <p>
          The Day Pillar&apos;s Earthly Branch is called the &quot;Marriage Palace&quot; (婚姻宮). The branch relationship
          here is considered the most important indicator for marital harmony — Six Harmony is ideal,
          while a Clash suggests fundamental friction.
        </p>

        <h3>Branch Relationships / 地支關係</h3>
        <p>We analyze Year, Month, and Day branches for six types of interactions:</p>
        <ul>
          <li><strong>六合 Six Harmony:</strong> Deepest bond (+3)</li>
          <li><strong>三合 Three Harmony:</strong> Elemental alliance (+2)</li>
          <li><strong>六冲 Clash:</strong> Direct opposition (−3)</li>
          <li><strong>六害 Harm:</strong> Hidden friction (−2)</li>
          <li><strong>三刑 Punishment:</strong> Karmic tension (−2)</li>
          <li><strong>六破 Destruction:</strong> Destabilizing (−1)</li>
        </ul>

        <h3>Elemental Complementarity / 五行互補</h3>
        <p>
          Ideally, one partner&apos;s dominant element supports the other&apos;s weak element, creating
          mutual nourishment. Shared weaknesses indicate areas where both partners may struggle.
        </p>

        <h3>Yin-Yang Balance / 陰陽平衡</h3>
        <p>
          Classical theory favors complementary polarity: a Yang-dominant male chart paired with
          a Yin-dominant female chart. Modern interpretation recognizes that balance matters more
          than rigid traditional roles.
        </p>

        <h3>Na Yin / 納音五行</h3>
        <p>
          Each year in the 60-year Jiazi cycle has a Na Yin element — a poetic &quot;sound element&quot; derived
          from the stem-branch combination. Compatible Na Yin elements suggest aligned life direction.
        </p>

        <h3>Scoring</h3>
        <p>
          Each factor scores from −3 (strongest conflict) to +3 (strongest harmony). Scores are
          normalized to a 0–100% scale. Ratings: Excellent (≥80%), Good (60–79%), Moderate (40–59%),
          Challenging (&lt;40%).
        </p>

        <div className="note-box">
          <strong>Note:</strong> Compatibility analysis reflects energetic tendencies based on birth time,
          not fixed destiny. It is one tool among many for understanding relationship dynamics.
        </div>
      </MethodologyModal>
    </main>
  );
}

function ReadingSections({ lines }: { lines: string[] }) {
  const sections: Array<{ title?: string; paragraphs: string[] }> = [];
  let current: { title?: string; paragraphs: string[] } = { paragraphs: [] };
  for (const line of lines) {
    if (line.startsWith("## ")) {
      if (current.title || current.paragraphs.length > 0) sections.push(current);
      current = { title: line.slice(3), paragraphs: [] };
    } else { current.paragraphs.push(line); }
  }
  if (current.title || current.paragraphs.length > 0) sections.push(current);
  return (
    <div className="reading-sections">
      {sections.map((section, idx) => (
        <div key={idx} className="reading-section">
          {section.title && <h4 className="reading-section-title">{section.title}</h4>}
          {section.paragraphs.map((p, pIdx) => (
            <p key={pIdx} className="reading-section-text">{p}</p>
          ))}
        </div>
      ))}
    </div>
  );
}
