"use client";

import { FormEvent, useState, useRef } from "react";
import {
  calculateZodiacReading,
  getAnimalFromDate,
  ANIMALS,
  REL_LABELS,
  type ZodiacReading,
  type DayForecast,
} from "@/lib/zodiac";
import {
  copyToClipboard,
  exportReadingAsPDF,
} from "@/lib/pdf-export";
import { MethodologyModal } from "@/components/MethodologyModal";

const RATING_LABELS: Record<string, string> = {
  "very-auspicious": "Very Auspicious",
  auspicious: "Auspicious",
  neutral: "Neutral",
  challenging: "Challenging",
  "very-challenging": "Very Challenging",
};

export default function ZodiacPage() {
  const [birthDate, setBirthDate] = useState("");
  const [reading, setReading] = useState<ZodiacReading | null>(null);
  const [error, setError] = useState("");
  const [copySuccess, setCopySuccess] = useState(false);
  const [expandedDay, setExpandedDay] = useState<string | null>(null);
  const [showMethodology, setShowMethodology] = useState(false);
  const resultPanelRef = useRef<HTMLElement>(null);

  const todayStr = new Date().toISOString().slice(0, 10);

  function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError("");
    setExpandedDay(null);
    if (!birthDate) { setError("Please enter your date of birth."); return; }
    try {
      setReading(calculateZodiacReading(birthDate));
    } catch (err) {
      setReading(null);
      setError(err instanceof Error ? err.message : "Something went wrong.");
    }
  }

  async function handleExportPDF() {
    if (!reading || !resultPanelRef.current) return;
    try { await exportReadingAsPDF(resultPanelRef.current, "zodiac-forecast.pdf"); }
    catch (err) { console.error("Zodiac PDF export failed:", err); }
  }

  function handleShareText() {
    if (!reading) return;
    const lines = [
      `Chinese Zodiac Reading — ${reading.animal.emoji} ${reading.animal.english} (${reading.animal.chinese})`,
      `Zodiac Year: ${reading.zodiacYear} | Element: ${reading.animal.element} | ${reading.animal.polarity}`,
      "",
      "28-Day Forecast:",
      ...reading.forecasts.map((f) => {
        const da = ANIMALS[f.dayAnimalIndex];
        return `${f.date} ${da.emoji} ${da.english} [${f.officer.chinese}${f.officer.english}] — ${RATING_LABELS[f.rating]}: ${f.brief}`;
      }),
      "",
      `Generated by 天機 Heavenly Secrets`,
    ];
    if (copyToClipboard(lines.join("\n"))) {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
  }

  // Live preview of animal as user picks date
  const previewAnimal = (() => {
    if (!birthDate) return null;
    try { return getAnimalFromDate(birthDate); } catch { return null; }
  })();

  return (
    <main className="page-shell">
      <section className="hero-panel">
        <div className="hero-zh">生肖</div>
        <div className="divider" />
        <div className="hero-en">Chinese Zodiac</div>
        <p>
          Discover your zodiac animal and view a 28-day daily forecast combining
          classical branch relationships with the Chinese almanac Day Officers (建除十二神).
        </p>
        <button type="button" className="methodology-trigger" onClick={() => setShowMethodology(true)}>
          How It Works
        </button>
      </section>

      <section className="workspace-grid">
        <form className="panel" onSubmit={handleSubmit}>
          <h2>Your Details / 資料</h2>

          <label>
            Date of Birth / 出生日期
            <input
              type="date"
              value={birthDate}
              onChange={(e) => setBirthDate(e.target.value)}
              required
            />
          </label>
          {previewAnimal && (
            <p className="input-hint">
              {previewAnimal.animal.emoji} {previewAnimal.animal.english} ({previewAnimal.animal.chinese}) — {previewAnimal.animal.element} {previewAnimal.animal.polarity}
              {(() => {
                const [y] = birthDate.split("-").map(Number);
                return previewAnimal.zodiacYear !== y
                  ? ` (born before 立春 Lichun — zodiac year ${previewAnimal.zodiacYear})`
                  : "";
              })()}
            </p>
          )}

          <button type="submit">Generate Forecast / 生成運勢</button>
          {error && <p className="error-msg">{error}</p>}
        </form>

        <section className="panel result-panel" ref={resultPanelRef}>
          <h2>Zodiac Forecast</h2>

          {!reading ? (
            <p className="placeholder">
              Enter your date of birth to discover your zodiac animal and 28-day daily forecast.
            </p>
          ) : (
            <>
              <div className="action-bar">
                <button type="button" onClick={handleExportPDF} className="action-btn export-btn">
                  ↓ Export PDF
                </button>
                <button
                  type="button"
                  onClick={handleShareText}
                  className={`action-btn share-btn ${copySuccess ? "copied" : ""}`}
                >
                  {copySuccess ? "✓ Copied to Clipboard" : "⧉ Copy & Share"}
                </button>
              </div>

              <div className="zodiac-profile">
                <div className="zodiac-profile-animal">{reading.animal.emoji}</div>
                <div className="zodiac-profile-info">
                  <h3>{reading.animal.chinese} {reading.animal.english}</h3>
                  <p className="zodiac-profile-meta">
                    {reading.animal.element} · {reading.animal.polarity} · Zodiac year {reading.zodiacYear}
                  </p>
                  <p className="zodiac-profile-traits">{reading.animal.traits}</p>
                  <div className="zodiac-profile-compat">
                    <span className="zodiac-compat-good">Harmonious: {reading.animal.compatible.join(", ")}</span>
                    <span className="zodiac-compat-bad">Challenging: {reading.animal.incompatible.join(", ")}</span>
                  </div>
                </div>
              </div>

              <div className="zodiac-forecast-section">
                <h3>28-Day Daily Forecast</h3>
                <div className="zodiac-forecast-legend">
                  <span className="zodiac-legend-dot zodiac-day--very-auspicious" /> Very Auspicious
                  <span className="zodiac-legend-dot zodiac-day--auspicious" /> Auspicious
                  <span className="zodiac-legend-dot zodiac-day--neutral" /> Neutral
                  <span className="zodiac-legend-dot zodiac-day--challenging" /> Challenging
                  <span className="zodiac-legend-dot zodiac-day--very-challenging" /> Very Challenging
                </div>
                <div className="zodiac-forecast-grid">
                  {reading.forecasts.map((f) => {
                    const da = ANIMALS[f.dayAnimalIndex];
                    const isToday = f.date === todayStr;
                    const isExpanded = expandedDay === f.date;
                    return (
                      <button
                        key={f.date}
                        type="button"
                        className={`zodiac-day zodiac-day--${f.rating}${isToday ? " zodiac-day--today" : ""}${isExpanded ? " zodiac-day--selected" : ""}`}
                        onClick={() => setExpandedDay(isExpanded ? null : f.date)}
                        title={`${f.date} — ${da.english} — ${f.officer.chinese}${f.officer.english}`}
                      >
                        <span className="zodiac-day-date">
                          {isToday ? "Today" : `${Number(f.date.slice(8))}/${Number(f.date.slice(5, 7))}`}
                        </span>
                        <span className="zodiac-day-animal">{da.emoji}</span>
                        <span className="zodiac-day-officer">{f.officer.chinese}</span>
                        <span className="zodiac-day-rel">
                          {f.relationships.filter((r) => r !== "none").map((r) => REL_LABELS[r].zh).join(" ") || "平"}
                        </span>
                      </button>
                    );
                  })}
                </div>

                {expandedDay && (() => {
                  const forecast = reading.forecasts.find((f) => f.date === expandedDay);
                  return forecast ? <DayDetail forecast={forecast} /> : null;
                })()}
              </div>

              <div className="zodiac-interpretation">
                <h3>Interpretation</h3>
                <ReadingSections lines={reading.interpretation} />
              </div>

              <div className="note-box">
                <p>Zodiac animal is determined by the 立春 (Lichun) solar term boundary (~Feb 3–5), not January 1st. Births in January or early February may fall under the previous year&apos;s animal.</p>
                <p>Daily forecast combines Earthly Branch (地支) zodiac relationships with the 12 Day Officers (建除十二神) from the Chinese almanac (黃曆).</p>
              </div>
            </>
          )}
        </section>
      </section>

      <MethodologyModal isOpen={showMethodology} onClose={() => setShowMethodology(false)} title="How Chinese Zodiac Forecasting Works / 生肖運勢原理">
        <h3>The Twelve Animals / 十二生肖</h3>
        <p>
          The Chinese zodiac assigns one of twelve animals to each year in a repeating cycle. Your birth date
          determines your zodiac animal, using the 立春 (Lichun) solar term as the year boundary — not January 1st.
          If you were born in January or early February, your zodiac animal may belong to the previous year.
        </p>

        <h3>Daily Earthly Branch Cycle / 日支循環</h3>
        <p>
          Beyond the yearly cycle, each day also carries an Earthly Branch — the same twelve branches that
          correspond to the twelve animals. Every 12 days, the full zodiac cycle repeats at the daily level.
          The interaction between your birth animal and the day&apos;s animal creates the basis for daily forecasting.
        </p>

        <h3>Classical Relationships / 地支關係</h3>
        <p>Chinese astrology defines six types of branch interactions:</p>
        <ul>
          <li><strong>六合 (Six Harmonies):</strong> The deepest one-to-one bond. Rat–Ox, Tiger–Pig, Rabbit–Dog, Dragon–Rooster, Snake–Monkey, Horse–Goat.</li>
          <li><strong>三合 (Three Harmonies):</strong> Elemental triangle alliances. Water (Rat, Dragon, Monkey), Wood (Tiger, Horse, Dog), Fire (Rabbit, Goat, Pig), Metal (Ox, Snake, Rooster).</li>
          <li><strong>六冲 (Six Clashes):</strong> Direct opposition — the strongest conflict. Rat–Horse, Ox–Goat, Tiger–Monkey, Rabbit–Rooster, Dragon–Dog, Snake–Pig.</li>
          <li><strong>六害 (Six Harms):</strong> Hidden, undermining friction.</li>
          <li><strong>三刑 (Three Punishments):</strong> Karmic tension. Tiger–Snake–Monkey, Ox–Dog–Goat, plus self-punishment for Rat, Rabbit, Horse, Rooster.</li>
          <li><strong>六破 (Six Destructions):</strong> Scattering, destabilizing energy.</li>
        </ul>

        <h3>Day Officers / 建除十二神</h3>
        <p>
          The Chinese almanac (黃曆/通勝) assigns one of twelve Day Officers to each day. This cycle is tied to the
          month&apos;s Earthly Branch and resets at each solar term. Each officer determines which activities are
          traditionally suitable (宜) or should be avoided (忌):
        </p>
        <table>
          <thead>
            <tr><th>Officer</th><th>Nature</th><th>Best For</th></tr>
          </thead>
          <tbody>
            <tr><td>建 Establish</td><td>Neutral</td><td>Planning, setting intentions</td></tr>
            <tr><td>除 Remove</td><td>Auspicious</td><td>Cleaning, medical treatment, breaking habits</td></tr>
            <tr><td>滿 Full</td><td>Auspicious</td><td>Celebrations, weddings, grand openings</td></tr>
            <tr><td>平 Balance</td><td>Neutral</td><td>Routine tasks, minor repairs</td></tr>
            <tr><td>定 Stable</td><td>Auspicious</td><td>Agreements, engagements, building</td></tr>
            <tr><td>執 Hold</td><td>Neutral</td><td>Construction, collecting, securing</td></tr>
            <tr><td>破 Break</td><td>Inauspicious</td><td>Demolition, surgery, ending situations</td></tr>
            <tr><td>危 Danger</td><td>Inauspicious</td><td>Prayer, reflection, spiritual practice</td></tr>
            <tr><td>成 Success</td><td>Auspicious</td><td>Business openings, contracts, weddings</td></tr>
            <tr><td>收 Receive</td><td>Auspicious</td><td>Collecting payments, closing deals</td></tr>
            <tr><td>開 Open</td><td>Auspicious</td><td>New beginnings, travel, moving house</td></tr>
            <tr><td>閉 Close</td><td>Inauspicious</td><td>Sealing, storage, meditation</td></tr>
          </tbody>
        </table>

        <h3>Combined Rating</h3>
        <p>
          Each day&apos;s overall rating combines the zodiac animal relationship (positive or negative) with the
          Day Officer&apos;s nature (auspicious, neutral, or inauspicious). A Six Harmony day falling on a
          Success officer is exceptionally favorable, while a Clash day on a Danger officer warrants extra caution.
        </p>

        <div className="note-box">
          <strong>Note:</strong> The daily forecast uses the sexagenary cycle (六十甲子) and the Jie (節) solar
          term boundaries for Day Officer calculation. The zodiac year starts at 立春 (Lichun, ~Feb 3–5),
          which is the astronomical start of spring in the Chinese calendar system.
        </div>
      </MethodologyModal>
    </main>
  );
}

function DayDetail({ forecast }: { forecast: DayForecast }) {
  const da = ANIMALS[forecast.dayAnimalIndex];
  const relLabels = forecast.relationships.map((r) => `${REL_LABELS[r].zh} ${REL_LABELS[r].en}`);
  return (
    <div className="zodiac-detail">
      <div className="zodiac-detail-header">
        <span className="zodiac-detail-date">{forecast.date}</span>
        <span className="zodiac-detail-animal">{da.emoji} {da.english} ({da.chinese})</span>
        <span className={`zodiac-detail-rating zodiac-day--${forecast.rating}`}>
          {RATING_LABELS[forecast.rating]}
        </span>
      </div>
      <div className="zodiac-detail-rels">
        {relLabels.map((label) => (
          <span key={label} className="zodiac-detail-rel-chip">{label}</span>
        ))}
        <span className="zodiac-detail-rel-chip zodiac-officer-chip">
          {forecast.officer.chinese} {forecast.officer.english}
        </span>
      </div>
      <p className="zodiac-detail-text">{forecast.detail.split("\n\n")[1]}</p>
      <div className="zodiac-detail-almanac">
        <div className="zodiac-almanac-col zodiac-almanac-good">
          <strong>宜 Suitable</strong>
          <ul>{forecast.officer.suitable.map((s) => <li key={s}>{s}</li>)}</ul>
        </div>
        <div className="zodiac-almanac-col zodiac-almanac-bad">
          <strong>忌 Avoid</strong>
          <ul>{forecast.officer.avoid.map((a) => <li key={a}>{a}</li>)}</ul>
        </div>
      </div>
    </div>
  );
}

function ReadingSections({ lines }: { lines: string[] }) {
  const sections: Array<{ title?: string; paragraphs: string[] }> = [];
  let current: { title?: string; paragraphs: string[] } = { paragraphs: [] };
  for (const line of lines) {
    if (line.startsWith("## ")) {
      if (current.title || current.paragraphs.length > 0) sections.push(current);
      current = { title: line.slice(3), paragraphs: [] };
    } else { current.paragraphs.push(line); }
  }
  if (current.title || current.paragraphs.length > 0) sections.push(current);
  return (
    <div className="reading-sections">
      {sections.map((section, idx) => (
        <div key={idx} className="reading-section">
          {section.title && <h4 className="reading-section-title">{section.title}</h4>}
          {section.paragraphs.map((p, pIdx) => (
            <p key={pIdx} className="reading-section-text">{p}</p>
          ))}
        </div>
      ))}
    </div>
  );
}
