"use client";

import { FormEvent, useMemo, useRef, useState } from "react";
import { calculateNumerology, NumerologyChart } from "@/lib/numerology";
import { copyToClipboard, exportReadingAsPDF } from "@/lib/pdf-export";
import { MethodologyModal } from "@/components/MethodologyModal";

type FormState = {
  name: string;
  birthDate: string;
  birthTime: string;
};

const ELEMENT_COLORS: Record<string, string> = {
  Wood: "var(--wood)",
  Fire: "var(--fire)",
  Earth: "var(--earth)",
  Metal: "var(--metal)",
  Water: "var(--water)",
};

const EMPTY_FORM: FormState = {
  name: "",
  birthDate: "",
  birthTime: "",
};

const CORE_NUMBER_LABELS: Record<number, string> = {
  1: "Pioneer", 2: "Diplomat", 3: "Creator", 4: "Builder", 5: "Adventurer",
  6: "Nurturer", 7: "Seeker", 8: "Powerhouse", 9: "Humanitarian",
  11: "Illuminator", 22: "Master Builder", 33: "Master Healer",
};

const LO_SHU_GRID_NUMBERS: number[][] = [
  [4, 9, 2],
  [3, 5, 7],
  [8, 1, 6],
];

export default function NumerologyPage() {
  const [form, setForm] = useState<FormState>(EMPTY_FORM);
  const [chart, setChart] = useState<NumerologyChart | null>(null);
  const [error, setError] = useState<string>("");
  const [copySuccess, setCopySuccess] = useState<boolean>(false);
  const [showMethodology, setShowMethodology] = useState(false);
  const resultPanelRef = useRef<HTMLDivElement>(null);

  const elementRows = useMemo(() => {
    if (!chart) return [];
    const total = Object.values(chart.elementBalance).reduce((s, c) => s + c, 0);
    return Object.entries(chart.elementBalance).map(([element, count]) => ({
      element,
      count,
      percent: Math.max(8, (count / Math.max(total, 1)) * 100),
    }));
  }, [chart]);

  // Set of numbers that are part of an active arrow (for highlighting)
  const arrowNumbers = useMemo(() => {
    if (!chart) return new Set<number>();
    const nums = new Set<number>();
    for (const arrow of chart.loShuArrows) {
      for (const n of arrow.numbers) nums.add(n);
    }
    return nums;
  }, [chart]);

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");

    try {
      const result = calculateNumerology({
        name: form.name.trim() || undefined,
        birthDate: form.birthDate,
        birthTime: form.birthTime || undefined,
      });
      setChart(result);
    } catch (submitError) {
      setChart(null);
      setError(
        submitError instanceof Error
          ? submitError.message
          : "Something went wrong while generating your reading.",
      );
    }
  }

  async function handleExportPDF() {
    if (!chart || !resultPanelRef.current) return;
    try {
      const fileName = form.name.trim() ? `${form.name.trim()}-numerology.pdf` : "numerology-reading.pdf";
      await exportReadingAsPDF(resultPanelRef.current, fileName);
    } catch (err) {
      console.error("PDF export failed:", err);
    }
  }

  function handleShareText() {
    if (!chart) return;
    const lines: string[] = [
      "═══════════════════════════════════",
      "  數理 · Mystic Numbers Reading",
      "═══════════════════════════════════",
      "",
    ];
    if (form.name.trim()) lines.push(`Name: ${form.name.trim()}`);
    lines.push(`Birth Date: ${form.birthDate}`);
    if (form.birthTime) lines.push(`Birth Time: ${form.birthTime}`);
    lines.push("");
    lines.push("── Core Numbers ──");
    lines.push(`Life Path: ${chart.lifePathNumber} (${CORE_NUMBER_LABELS[chart.lifePathNumber] ?? ""})`);
    lines.push(`Birthday: ${chart.birthdayNumber}`);
    if (chart.expressionNumber !== null) lines.push(`Expression: ${chart.expressionNumber}`);
    if (chart.soulUrgeNumber !== null) lines.push(`Soul Urge: ${chart.soulUrgeNumber}`);
    if (chart.personalityNumber !== null) lines.push(`Personality: ${chart.personalityNumber}`);
    lines.push(`Personal Year: ${chart.personalYearNumber}`);
    lines.push("");
    lines.push("── Lo Shu Grid ──");
    if (chart.loShuArrows.length > 0) {
      lines.push(`Arrows: ${chart.loShuArrows.map((a) => `${a.name} (${a.nameZh})`).join(", ")}`);
    }
    if (chart.missingNumbers.length > 0) {
      lines.push(`Missing: ${chart.missingNumbers.join(", ")}`);
    }
    lines.push("");
    lines.push("── Five Elements ──");
    lines.push(`Dominant: ${chart.dominantElement}`);
    lines.push(`Life Path Element: ${chart.lifePathElement}`);
    lines.push("");
    for (const line of chart.interpretation) {
      if (line.startsWith("## ")) {
        lines.push("");
        lines.push(`── ${line.slice(3)} ──`);
      } else {
        lines.push(line);
      }
    }
    lines.push("");
    lines.push("───────────────────────────────────");
    lines.push("Generated by 神圣秘密 Divine Secrets");

    const success = copyToClipboard(lines.join("\n"));
    if (success) {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
  }

  return (
    <main className="page-shell">
      <section className="hero-panel">
        <div className="hero-zh">數理</div>
        <div className="divider" />
        <div className="hero-en">Mystic Numbers</div>
        <p>
          Reveal your numerological profile through both Eastern and Western traditions — from Pythagorean life path to the ancient Lo Shu Grid.
        </p>
        <button type="button" className="methodology-trigger" onClick={() => setShowMethodology(true)}>
          How It Works
        </button>
      </section>

      <section className="workspace-grid">
        <form className="panel" onSubmit={handleSubmit}>
          <h2>Birth Profile / 出生資料</h2>
          <label>
            Name / 姓名 (optional, for name-based numbers)
            <input
              type="text"
              value={form.name}
              onChange={(event) => setForm((prev) => ({ ...prev, name: event.target.value }))}
              placeholder="e.g. Mei Ling Chen"
            />
          </label>

          <label>
            Date of Birth / 生日
            <input
              type="date"
              value={form.birthDate}
              onChange={(event) => setForm((prev) => ({ ...prev, birthDate: event.target.value }))}
              required
            />
          </label>

          <label>
            Time of Birth / 出生時間 (optional)
            <input
              type="time"
              value={form.birthTime}
              onChange={(event) => setForm((prev) => ({ ...prev, birthTime: event.target.value }))}
            />
          </label>

          <button type="submit">Generate Numerology Reading / 排數理</button>
          {error ? <p className="error-msg">{error}</p> : null}
        </form>

        <section className="panel result-panel" ref={resultPanelRef}>
          <h2>Reading Output</h2>

          {!chart ? (
            <p className="placeholder">
              Submit the form to reveal your numerological profile combining Eastern and Western wisdom.
            </p>
          ) : (
            <>
              <div className="action-bar">
                <button type="button" onClick={handleExportPDF} className="action-btn export-btn">
                  ↓ Export PDF
                </button>
                <button
                  type="button"
                  onClick={handleShareText}
                  className={`action-btn share-btn ${copySuccess ? "copied" : ""}`}
                >
                  {copySuccess ? "✓ Copied to Clipboard" : "⧉ Copy & Share"}
                </button>
              </div>

              <div className="meta-row">
                <p>
                  <span>Life Path:</span> {chart.lifePathNumber} — {CORE_NUMBER_LABELS[chart.lifePathNumber] ?? ""}
                </p>
                <p>
                  <span>Life Path Element:</span> {chart.lifePathElement}
                </p>
                <p>
                  <span>Dominant Element:</span> {chart.dominantElement}
                </p>
                {chart.birthHourElement ? (
                  <p>
                    <span>Birth Hour Element:</span> {chart.birthHourElement}
                  </p>
                ) : null}
              </div>

              {/* Core Numbers Grid */}
              <div className="numerology-core-grid">
                <CoreNumberCard
                  label="Life Path"
                  labelZh="生命靈數"
                  number={chart.lifePathNumber}
                  keyword={CORE_NUMBER_LABELS[chart.lifePathNumber] ?? ""}
                />
                <CoreNumberCard
                  label="Birthday"
                  labelZh="生日數"
                  number={chart.birthdayNumber}
                  keyword={CORE_NUMBER_LABELS[chart.birthdayNumber] ?? ""}
                />
                <CoreNumberCard
                  label="Expression"
                  labelZh="表達數"
                  number={chart.expressionNumber}
                  keyword={chart.expressionNumber !== null ? (CORE_NUMBER_LABELS[chart.expressionNumber] ?? "") : ""}
                />
                <CoreNumberCard
                  label="Soul Urge"
                  labelZh="靈魂數"
                  number={chart.soulUrgeNumber}
                  keyword={chart.soulUrgeNumber !== null ? (CORE_NUMBER_LABELS[chart.soulUrgeNumber] ?? "") : ""}
                />
                <CoreNumberCard
                  label="Personality"
                  labelZh="個性數"
                  number={chart.personalityNumber}
                  keyword={chart.personalityNumber !== null ? (CORE_NUMBER_LABELS[chart.personalityNumber] ?? "") : ""}
                />
                <CoreNumberCard
                  label="Personal Year"
                  labelZh="流年數"
                  number={chart.personalYearNumber}
                  keyword={CORE_NUMBER_LABELS[chart.personalYearNumber] ?? ""}
                />
              </div>

              {/* Lo Shu Grid */}
              <div className="loshu-section">
                <h3>Lo Shu Grid / 洛書九宮</h3>
                <p className="luck-subtitle">
                  Your birth date digits mapped onto the ancient Chinese magic square. Highlighted cells form Arrows of Strength.
                </p>
                <div className="loshu-grid">
                  {LO_SHU_GRID_NUMBERS.map((row, rowIdx) =>
                    row.map((posNum, colIdx) => {
                      const count = chart.loShuGrid[rowIdx][colIdx];
                      const isArrow = arrowNumbers.has(posNum);
                      return (
                        <div
                          key={`${rowIdx}-${colIdx}`}
                          className={`loshu-cell ${isArrow && count > 0 ? "has-arrow" : ""} ${count === 0 ? "is-empty" : ""}`}
                        >
                          <span className="loshu-position">{posNum}</span>
                          <span className="loshu-count">{count > 0 ? count : "—"}</span>
                        </div>
                      );
                    })
                  )}
                </div>
                {chart.loShuArrows.length > 0 ? (
                  <div className="loshu-arrows">
                    {chart.loShuArrows.map((arrow) => (
                      <span key={arrow.name} className="loshu-arrow-badge">
                        {arrow.nameZh} {arrow.name} ({arrow.numbers.join("-")})
                      </span>
                    ))}
                  </div>
                ) : (
                  <p className="loshu-missing">No complete arrows — strengths are distributed individually.</p>
                )}
                {chart.missingNumbers.length > 0 ? (
                  <p className="loshu-missing">
                    Missing numbers: {chart.missingNumbers.join(", ")} — areas for conscious growth.
                  </p>
                ) : (
                  <p className="loshu-missing">All numbers 1–9 are present — a rare and well-rounded grid.</p>
                )}
              </div>

              {/* Chinese Number Meanings */}
              <div className="loshu-section">
                <h3>Chinese Number Symbolism / 數字象徵</h3>
                <p className="luck-subtitle">
                  Each digit carries symbolic meaning rooted in Chinese language and tradition.
                </p>
                <div className="number-meanings-grid">
                  {chart.numberMeanings.map((nm) => (
                    <div key={nm.number} className="number-meaning-card">
                      <span className="nm-digit">{nm.number}</span>
                      <span className="nm-chinese">{nm.chinese}</span>
                      <p className="nm-text">{nm.meaning}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Element Balance */}
              <div className="element-chart">
                <h3>Five Elements Balance / 五行分析</h3>
                {elementRows.map((row) => (
                  <div key={row.element} className="element-row">
                    <div className="element-label">
                      <span>{row.element}</span>
                      <strong>{row.count}</strong>
                    </div>
                    <div className="bar-track">
                      <div
                        className="bar-fill"
                        style={{
                          width: `${row.percent}%`,
                          backgroundColor: ELEMENT_COLORS[row.element],
                        }}
                      />
                    </div>
                  </div>
                ))}
                <p className="element-summary">
                  Dominant: <strong>{chart.dominantElement}</strong>
                  {chart.birthHourElement ? <> | Birth Hour: <strong>{chart.birthHourElement}</strong></> : null}
                  {" "}| Life Path Element: <strong>{chart.lifePathElement}</strong>
                </p>
              </div>

              {/* Interpretation */}
              <div className="interpretation">
                <h3>Full Reading</h3>
                <ReadingSections lines={chart.interpretation} />
              </div>

              {/* Notes */}
              <div className="note-box">
                {chart.notes.map((note) => (
                  <p key={note}>{note}</p>
                ))}
              </div>
            </>
          )}
        </section>
      </section>

      <MethodologyModal isOpen={showMethodology} onClose={() => setShowMethodology(false)} title="How Numerology Works / 數理計算原理">
        <h3>Two Traditions, One Profile</h3>
        <p>
          This reading combines Western Pythagorean numerology with the ancient Chinese Lo Shu Grid system,
          giving you a cross-cultural view of the energies encoded in your birth date and name.
        </p>

        <h3>Western Pythagorean System</h3>
        <h4>Life Path Number</h4>
        <p>
          Your most important number. Calculated by reducing your full date of birth (DD + MM + YYYY) to a single
          digit through repeated addition. For example, 1990-03-15 → 1+9+9+0 + 0+3 + 1+5 = 28 → 2+8 = 10 → 1+0 = <strong>1</strong>.
          Master numbers (11, 22, 33) are preserved and not reduced further, as they carry amplified vibrations.
        </p>
        <h4>Expression Number</h4>
        <p>
          Derived from your full name using the Pythagorean letter-to-number mapping (A=1, B=2, ... I=9, J=1, K=2, etc.).
          All letter values are summed and reduced. This number reveals your natural talents and abilities.
        </p>
        <h4>Soul Urge Number</h4>
        <p>
          Calculated from only the <strong>vowels</strong> (A, E, I, O, U) in your name. Represents your inner desires,
          motivations, and what truly drives you at the heart level.
        </p>
        <h4>Personality Number</h4>
        <p>
          Calculated from only the <strong>consonants</strong> in your name. Represents how others perceive you —
          the outer personality you project to the world.
        </p>

        <h3>Personal Year Cycle</h3>
        <p>
          Your personal year number is calculated by adding your birth day + birth month + the current calendar year,
          then reducing. It cycles through 1–9, indicating the theme and energy of each year in your life.
        </p>

        <h3>Chinese Lo Shu Grid / 洛書九宮格</h3>
        <p>
          The Lo Shu Grid is a 3×3 magic square discovered on the back of a divine turtle, according to legend.
          The numbers 1-9 are arranged so each row, column, and diagonal sums to 15:
        </p>
        <table>
          <tbody>
            <tr><td>4</td><td>9</td><td>2</td></tr>
            <tr><td>3</td><td>5</td><td>7</td></tr>
            <tr><td>8</td><td>1</td><td>6</td></tr>
          </tbody>
        </table>
        <p>
          Each digit from your birth date is placed into its corresponding grid position. The frequency of each
          number reveals character strengths, while empty positions indicate areas for growth.
        </p>

        <h3>Arrows of Strength &amp; Weakness</h3>
        <p>
          When all three numbers in a row, column, or diagonal are present in your birth date, they form an
          <strong>Arrow of Strength</strong> (e.g., 4-5-6 = Arrow of Willpower). Conversely, if all three positions
          are empty, an Arrow of Weakness is formed. There are 8 possible arrows in the grid.
        </p>

        <h3>Chinese Five Element Mapping</h3>
        <p>
          Each digit also maps to one of the Five Elements in the Chinese system:
        </p>
        <ul>
          <li><strong>Water (水):</strong> 1, 6</li>
          <li><strong>Fire (火):</strong> 2, 7</li>
          <li><strong>Wood (木):</strong> 3, 8</li>
          <li><strong>Metal (金):</strong> 4, 9</li>
          <li><strong>Earth (土):</strong> 5, 0</li>
        </ul>
        <p>
          The element balance from your birth date digits and Life Path number reveals your elemental constitution,
          similar to the Five Element analysis in BaZi but derived purely from numbers.
        </p>

        <div className="note-box">
          <strong>Note:</strong> Name-based numbers (Expression, Soul Urge, Personality) require a name input.
          If no name is provided, only date-based numbers are calculated.
        </div>
      </MethodologyModal>
    </main>
  );
}

// ─── Helper Components ─────────────────────────────────────────────────

function CoreNumberCard({
  label,
  labelZh,
  number,
  keyword,
}: {
  label: string;
  labelZh: string;
  number: number | null;
  keyword: string;
}) {
  return (
    <article className="numerology-number-card">
      <p className="number-label">{label}</p>
      <p className="number-label-zh">{labelZh}</p>
      <p className="number-value">{number !== null ? number : "N/A"}</p>
      <p className="number-keyword">{number !== null ? keyword : "Requires name"}</p>
    </article>
  );
}

function ReadingSections({ lines }: { lines: string[] }) {
  const sections: Array<{ title?: string; paragraphs: string[] }> = [];
  let current: { title?: string; paragraphs: string[] } = { paragraphs: [] };

  for (const line of lines) {
    if (line.startsWith("## ")) {
      if (current.title || current.paragraphs.length > 0) {
        sections.push(current);
      }
      current = { title: line.slice(3), paragraphs: [] };
    } else {
      current.paragraphs.push(line);
    }
  }
  if (current.title || current.paragraphs.length > 0) {
    sections.push(current);
  }

  return (
    <div className="reading-sections">
      {sections.map((section, idx) => (
        <div key={idx} className="reading-section">
          {section.title ? <h4 className="reading-section-title">{section.title}</h4> : null}
          {section.paragraphs.map((p, pIdx) => (
            <p key={pIdx} className="reading-section-text">{p}</p>
          ))}
        </div>
      ))}
    </div>
  );
}
